[rank0]:[E ProcessGroupNCCL.cpp:523] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=4, Timeout(ms)=600000) ran for 60081
1 milliseconds before timing out.                                                                                                                                                        
[rank0]:[E ProcessGroupNCCL.cpp:537] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/inco
mplete data.                                                                                                                                                                             
[rank0]:[E ProcessGroupNCCL.cpp:543] To avoid data inconsistency, we are taking the entire process down.                                                                                 
[rank1]:[E ProcessGroupNCCL.cpp:523] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=4, Timeout(ms)=600000) ran for 60082
0 milliseconds before timing out.                                                                                                                                                        
[rank1]:[E ProcessGroupNCCL.cpp:537] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/inco
mplete data.                                                                                                                                                                             
[rank1]:[E ProcessGroupNCCL.cpp:543] To avoid data inconsistency, we are taking the entire process down.                                                                                 
[rank3]:[E ProcessGroupNCCL.cpp:523] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=4, Timeout(ms)=600000) ran for 60082
3 milliseconds before timing out.                                                                                                                                                        
[rank3]:[E ProcessGroupNCCL.cpp:537] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/inco
mplete data.                                                                                                                                                                             
[rank3]:[E ProcessGroupNCCL.cpp:543] To avoid data inconsistency, we are taking the entire process down.                                                                                 
[rank0]:[E ProcessGroupNCCL.cpp:1182] [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER
, NumelIn=1, NumelOut=4, Timeout(ms)=600000) ran for 600811 milliseconds before timing out.                                                                                              
Exception raised from checkTimeout at /opt/conda/conda-bld/pytorch_1708025845206/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:525 (most recent call first):                     
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7fcdb0701d87 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libc10.so)                
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1e6 (0x7fcdb18c64d6 in /u/ryanxli/anaconda3/envs/zsnew/
lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)                                                                                                                                 
frame #2: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x19d (0x7fcdb18c9a2d in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)                  
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x119 (0x7fcdb18ca629 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)                 
frame #4: <unknown function> + 0xd3e95 (0x7fcdfd174e95 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/../../../.././libstdc++.so.6)                           
frame #5: <unknown function> + 0x81ca (0x7fce1b7251ca in /lib64/libpthread.so.0)                                                                                                         
frame #6: clone + 0x43 (0x7fce1ac07e73 in /lib64/libc.so.6)                                                                                                                              
                                                                                                                                                                                         
[rank1]:[E ProcessGroupNCCL.cpp:1182] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER
, NumelIn=1, NumelOut=4, Timeout(ms)=600000) ran for 600820 milliseconds before timing out.                                                                                              
Exception raised from checkTimeout at /opt/conda/conda-bld/pytorch_1708025845206/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:525 (most recent call first):                     
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f44ca8f1d87 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libc10.so)                
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1e6 (0x7f44cbab64d6 in /u/ryanxli/anaconda3/envs/zsnew/
lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)                                                                                                                                 
frame #2: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x19d (0x7f44cbab9a2d in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)                  
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x119 (0x7f44cbaba629 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)                 
frame #4: <unknown function> + 0xd3e95 (0x7f4517364e95 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/../../../.././libstdc++.so.6)                           
frame #5: <unknown function> + 0x81ca (0x7f453591b1ca in /lib64/libpthread.so.0)                                                                                                         
frame #6: clone + 0x43 (0x7f4534dfde73 in /lib64/libc.so.6)                                                                                                                              
                                                                                                                                                                                         
[rank3]:[E ProcessGroupNCCL.cpp:1182] [Rank 3] NCCL watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER
, NumelIn=1, NumelOut=4, Timeout(ms)=600000) ran for 600823 milliseconds before timing out.                                                                                              
Exception raised from checkTimeout at /opt/conda/conda-bld/pytorch_1708025845206/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:525 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f12129e8d87 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1e6 (0x7f1213bad4d6 in /u/ryanxli/anaconda3/envs/zsnew$
lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x19d (0x7f1213bb0a2d in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x119 (0x7f1213bb1629 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3e95 (0x7f125f45be95 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x81ca (0x7f127da0c1ca in /lib64/libpthread.so.0)
frame #6: clone + 0x43 (0x7f127ceeee73 in /lib64/libc.so.6)


terminate called after throwing an instance of 'c10::DistBackendError'
terminate called after throwing an instance of 'c10::DistBackendError'
terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=4, Ti
meout(ms)=600000) ran for 600820 milliseconds before timing out.
Exception raised from checkTimeout at /opt/conda/conda-bld/pytorch_1708025845206/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:525 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f44ca8f1d87 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1e6 (0x7f44cbab64d6 in /u/ryanxli/anaconda3/envs/zsnew/
lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x19d (0x7f44cbab9a2d in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x119 (0x7f44cbaba629 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3e95 (0x7f4517364e95 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x81ca (0x7f453591b1ca in /lib64/libpthread.so.0)
frame #6: clone + 0x43 (0x7f4534dfde73 in /lib64/libc.so.6)

Exception raised from ncclCommWatchdog at /opt/conda/conda-bld/pytorch_1708025845206/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1186 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f44ca8f1d87 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe191e1 (0x7f44cb80f1e1 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xd3e95 (0x7f4517364e95 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #3: <unknown function> + 0x81ca (0x7f453591b1ca in /lib64/libpthread.so.0)
frame #4: clone + 0x43 (0x7f4534dfde73 in /lib64/libc.so.6)

  what():  [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=4, Ti
meout(ms)=600000) ran for 600811 milliseconds before timing out.
Exception raised from checkTimeout at /opt/conda/conda-bld/pytorch_1708025845206/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:525 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7fcdb0701d87 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1e6 (0x7fcdb18c64d6 in /u/ryanxli/anaconda3/envs/zsnew/
lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x19d (0x7fcdb18c9a2d in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x119 (0x7fcdb18ca629 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3e95 (0x7fcdfd174e95 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x81ca (0x7fce1b7251ca in /lib64/libpthread.so.0)
frame #6: clone + 0x43 (0x7fce1ac07e73 in /lib64/libc.so.6)

Exception raised from ncclCommWatchdog at /opt/conda/conda-bld/pytorch_1708025845206/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1186 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7fcdb0701d87 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe191e1 (0x7fcdb161f1e1 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xd3e95 (0x7fcdfd174e95 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #3: <unknown function> + 0x81ca (0x7fce1b7251ca in /lib64/libpthread.so.0)
frame #4: clone + 0x43 (0x7fce1ac07e73 in /lib64/libc.so.6)
  what():
[Rank 3] NCCL watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=4, Timeout(ms)=6
00000) ran for 600823 milliseconds before timing out.
Exception raised from checkTimeout at /opt/conda/conda-bld/pytorch_1708025845206/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:525 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f12129e8d87 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1e6 (0x7f1213bad4d6 in /u/ryanxli/anaconda3/envs/zsnew/
lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x19d (0x7f1213bb0a2d in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x119 (0x7f1213bb1629 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3e95 (0x7f125f45be95 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x81ca (0x7f127da0c1ca in /lib64/libpthread.so.0)
frame #6: clone + 0x43 (0x7f127ceeee73 in /lib64/libc.so.6)

Exception raised from ncclCommWatchdog at /opt/conda/conda-bld/pytorch_1708025845206/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1186 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f12129e8d87 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe191e1 (0x7f12139061e1 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xd3e95 (0x7f125f45be95 in /u/ryanxli/anaconda3/envs/zsnew/lib/python3.12/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #3: <unknown function> + 0x81ca (0x7f127da0c1ca in /lib64/libpthread.so.0)
frame #4: clone + 0x43 (0x7f127ceeee73 in /lib64/libc.so.6)
